// generated by src/lib/vocab/community/community.schema.ts

export interface Community {
	community_id: number;
	type: 'standard' | 'personal';
	name: string;
	settings: {
		hue: number;
		defaultRoleId: number;
		instance?: {
			allowedAccountNames?: string[];
		};
	};
	created: Date;
	updated: Date | null;
}
export interface CommunitySettings {
	hue: number;
	defaultRoleId: number;
	instance?: {
		allowedAccountNames?: string[];
	};
}
export interface InitialCommunitySettings {
	hue: number;
}

// generated by src/lib/vocab/community/community.schema.ts
