// generated by src/lib/vocab/community/community.schema.ts

/**
 *
 * 		Communities represent the membrane around the places Personas can interact with each other or with system level data.
 * 		They have self contained governance and ownership of Spaces within them.
 * 		By default they are hidden & undiscoverable and are only visible to a user once a Persona has been invited in.
 *
 */
export interface Community {
	community_id: number;
	type: 'standard' | 'personal';
	name: string;
	/**
	 *
	 * 		A nested set of attributes on Community. Holds all community level settings.
	 *
	 */
	settings: CommunitySettings;
	created: Date;
	updated: Date | null;
}
/**
 *
 * 		A nested set of attributes on Community. Holds all community level settings.
 *
 */
export interface CommunitySettings {
	hue: number;
	defaultRoleId: number;
	instance?: {
		allowedAccountNames?: string[];
	};
}
/**
 *
 * 		A subset of CommunitySettings needed for defaults at the time of Community creation.
 *
 */
export interface InitialCommunitySettings {
	hue: number;
}

// generated by src/lib/vocab/community/community.schema.ts
