// generated by src/lib/vocab/community/community.schema.ts

export interface Community {
	community_id: number;
	type: 'standard' | 'personal';
	name: string;
	settings: {
		hue: number;
	};
	created: Date;
	updated: Date | null;
}
export interface CommunitySettings {
	hue: number;
}

// generated by src/lib/vocab/community/community.schema.ts
