import type {PackageJson} from '@grogarden/gro/package_json.js';

export const package_json = {
	name: '@feltjs/felt',
	version: '0.9.1',
	license: 'MIT',
	description: 'a programmable platform for hobbyists and human-scale communities 💚',
	author: {name: 'feltjs', email: 'team@felt.social', url: 'https://felt.social'},
	homepage: 'https://github.com/feltjs/felt',
	repository: {type: 'git', url: 'git+https://github.com/feltjs/felt.git'},
	bugs: {url: 'https://github.com/feltjs/felt/issues'},
	scripts: {
		dev: 'gro dev',
		build: 'gro build',
		test: 'gro test',
		deploy: 'gro deploy',
		start: 'node dist_server/server/server.js',
		after_deploy: 'node dist_server/infra/after_deploy.js',
	},
	type: 'module',
	engines: {node: '>=20.7'},
	peerDependencies: {'@sveltejs/kit': '*'},
	devDependencies: {
		'@changesets/changelog-git': '^0.1.14',
		'@feltjs/eslint-config': '^0.4.1',
		'@feltjs/felt_mural': '^0.4.0',
		'@fuz.dev/fuz': '^0.75.4',
		'@fuz.dev/fuz_contextmenu': '^0.4.2',
		'@fuz.dev/fuz_dialog': '^0.3.2',
		'@fuz.dev/fuz_library': '^0.15.2',
		'@fuz.dev/svelte_intersect': '^0.5.1',
		'@grogarden/gro': '^0.96.4',
		'@ryanatkn/json-schema-to-typescript': '^11.1.5',
		'@sveltejs/adapter-node': '^1.3.1',
		'@sveltejs/kit': '^1.27.1',
		'@sveltejs/package': '^2.2.2',
		'@types/body-parser': '^1.19.3',
		'@types/cookie': '^0.5.2',
		'@types/cookie-signature': '^1.1.0',
		'@types/node': '^20.8.0',
		'@types/throttle-debounce': '^5.0.0',
		'@types/ws': '^8.5.6',
		'@typescript-eslint/eslint-plugin': '^6.7.4',
		'@typescript-eslint/parser': '^6.7.4',
		eslint: '^8.50.0',
		'eslint-plugin-svelte': '^2.33.2',
		eventemitter3: '^5.0.1',
		prettier: '^3.0.3',
		'prettier-plugin-svelte': '^3.0.3',
		'strict-event-emitter-types': '^2.0.0',
		svast: '^0.2.0',
		'svelte-check': '^3.5.2',
		tslib: '^2.6.2',
		typescript: '^5.2.2',
		uvu: '^0.5.6',
		zod: '^3.22.2',
	},
	dependencies: {
		'@feltcoop/svelte-gettable-stores': '^0.2.0',
		'@grogarden/util': '^0.15.2',
		'@polka/send-type': '^0.5.2',
		ajv: '^8.12.0',
		'ajv-keywords': '^5.1.0',
		'body-parser': '^1.20.2',
		cookie: '^0.5.0',
		'cookie-signature': '^1.2.1',
		'date-fns': '^2.30.0',
		dequal: '^2.0.3',
		dotenv: '^16.3.1',
		'estree-walker': '^3.0.3',
		kleur: '^4.1.5',
		ley: '^0.8.1',
		polka: '^0.5.2',
		postgres: '^3.3.5',
		regexparam: '^2.0.1',
		'svast-stringify': '^0.1.0',
		svelte: '^4.2.2',
		'svelte-parse': '^0.1.0',
		'throttle-debounce': '^5.0.0',
		ws: '^8.14.2',
	},
	optionalDependencies: {bufferutil: '^4.0.3', 'utf-8-validate': '^5.0.5'},
	eslintConfig: {root: true, extends: '@feltjs', rules: {'no-console': 1}},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [{files: 'package.json', options: {useTabs: false}}],
	},
	files: ['dist'],
	exports: {
		'./package.js': {default: './dist/package.js', types: './dist/package.d.ts'},
		'./docs/Docs.svelte': {
			svelte: './dist/docs/Docs.svelte',
			types: './dist/docs/Docs.svelte.d.ts',
		},
		'./docs/docs.js': {default: './dist/docs/docs.js', types: './dist/docs/docs.d.ts'},
		'./ui/app.js': {default: './dist/ui/app.js', types: './dist/ui/app.js'},
		'./ui/components.js': {default: './dist/ui/components.js', types: './dist/ui/components.js'},
		'./ui/ErrorMessage.svelte': {
			svelte: './dist/ui/ErrorMessage.svelte',
			types: './dist/ui/ErrorMessage.svelte.d.ts',
		},
		'./ui/HttpApiClient.js': {
			default: './dist/ui/HttpApiClient.js',
			types: './dist/ui/HttpApiClient.js',
		},
		'./ui/mutations.js': {default: './dist/ui/mutations.js', types: './dist/ui/mutations.js'},
		'./ui/services.js': {default: './dist/ui/services.js', types: './dist/ui/services.js'},
		'./ui/style.css': {default: './dist/ui/style.css'},
		'./ui/ui.js': {default: './dist/ui/ui.js', types: './dist/ui/ui.js'},
		'./util/deserialize.js': {
			default: './dist/util/deserialize.js',
			types: './dist/util/deserialize.d.ts',
		},
		'./util/query.js': {default: './dist/util/query.js', types: './dist/util/query.d.ts'},
		'./vocab/schemas.js': {default: './dist/vocab/schemas.js', types: './dist/vocab/schemas.d.ts'},
		'./vocab/action/actions.js': {
			default: './dist/vocab/action/actions.js',
			types: './dist/vocab/action/actions.d.ts',
		},
		'./vocab/account/account.js': {
			default: './dist/vocab/account/account.js',
			types: './dist/vocab/account/account.d.ts',
		},
	},
} satisfies PackageJson;
