// generated by src/lib/vocab/assignment/assignment.schema.ts

/**
 *
 * 	 Describes the relationship between a Persona and Role within a given Hub.
 * 	 A Persona must have at least 1 assignment to be in a Hub and see it in the nav.
 * 	 When initially joining a Hub, Personas are given an Assignment to the default Role.
 *
 */
export interface Assignment {
	assignment_id: number;
	persona_id: number;
	hub_id: number;
	role_id: number;
	created: Date;
}

// generated by src/lib/vocab/assignment/assignment.schema.ts
