// generated by src/lib/vocab/account/account.schema.ts

import type {EntityData} from '$lib/vocab/entity/entityData';
import type {AccountPersona, ClientPersona} from '$lib/vocab/persona/persona';
import type {Community} from '$lib/vocab/community/community';
import type {Entity} from '$lib/vocab/entity/entity';
import type {Role} from '$lib/vocab/role/role';
import type {Space} from '$lib/vocab/space/space';
import type {Assignment} from '$lib/vocab/assignment/assignment';
import type {Policy} from '$lib/vocab/policy/policy';

export interface Account {
	account_id: number;
	name: string;
	password: string;
	settings: {
		darkmode?: boolean;
	};
	created: Date;
	updated: Date | null;
}
export interface AccountSettings {
	darkmode?: boolean;
}
export interface ClientAccount {
	account_id: number;
	name: string;
	settings: {
		darkmode?: boolean;
	};
	created: Date;
	updated: Date | null;
}
export interface ClientAccountSession {
	account: ClientAccount;
	sessionPersonas: AccountPersona[];
	communities: Community[];
	roles: Role[];
	spaces: Space[];
	directories: Array<Entity & {data: EntityData}>;
	assignments: Assignment[];
	policies: Policy[];
	personas: ClientPersona[];
	guest?: false;
}
export interface ClientGuestSession {
	guest: true;
}
export type ClientSession = ClientAccountSession | ClientGuestSession;

// generated by src/lib/vocab/account/account.schema.ts
