// generated by src/lib/vocab/account/account.schema.ts

export interface AccountModel {
	account_id: number;
	name: string;
	settings: {
		darkmode?: boolean;
	};
	created: Date;
	updated: Date | null;
}
export interface Account {
	account_id: number;
	name: string;
	password: string;
	settings: {
		darkmode?: boolean;
	};
	created: Date;
	updated: Date | null;
}
export interface AccountSettings {
	darkmode?: boolean;
}

// generated by src/lib/vocab/account/account.schema.ts
