// generated by src/lib/vocab/tie/tie.schema.ts

export interface Tie {
	tie_id: number;
	source_id: number;
	dest_id: number;
	type: string;
	created: Date;
}

// generated by src/lib/vocab/tie/tie.schema.ts
