// generated by src/lib/vocab/tie/tie.schema.ts

export interface Tie {
	source_id: number;
	dest_id: number;
	type: string;
	created: Date;
	updated: Date | null;
}

// generated by src/lib/vocab/tie/tie.schema.ts
