// These are defined here for covenience and used in the `PermissionNameSchema`.
export const permissionNames = [
	'Ephemera',
	'UpdateHub',
	'DeleteHub',
	'InviteToHub',
	'KickFromHub',
	'CreateRole',
	'UpdateRole',
	'DeleteRole',
	'CreateAssignment',
	'DeleteAssignment',
	'CreateSpace',
	'UpdateSpace',
	'DeleteSpace',
	'CreateEntity',
	'CreatePolicy',
	'DeletePolicy',
	'UpdatePolicy',
];
