// generated by src/lib/vocab/permission/permission.schema.ts

export type PermissionName =
	| 'Ephemera'
	| 'UpdateHub'
	| 'DeleteHub'
	| 'InviteToHub'
	| 'KickFromHub'
	| 'CreateRole'
	| 'UpdateRole'
	| 'DeleteRole'
	| 'CreateAssignment'
	| 'DeleteAssignment'
	| 'CreateSpace'
	| 'UpdateSpace'
	| 'DeleteSpace'
	| 'CreateEntity'
	| 'CreatePolicy'
	| 'DeletePolicy'
	| 'UpdatePolicy';

// generated by src/lib/vocab/permission/permission.schema.ts
