// generated by src/lib/vocab/persona/persona.schema.ts

export interface PersonaParams {
	name: string;
}
export interface Persona {
	persona_id: number;
	account_id?: number;
	community_id: number;
	type: 'account' | 'community';
	name: string;
	icon?: string;
	created: Date;
	updated: Date | null;
}

// generated by src/lib/vocab/persona/persona.schema.ts
