// generated by src/lib/vocab/policy/policy.schema.ts

import type {Flavored} from '@feltjs/util';

export type PolicyId = Flavored<number, 'PolicyId'>;

/**
 *
 * 		Policies are associated with Roles to describe the actions a Role is able to take with the system.
 * 		Permissions are the enumeration of the those actions, often 1:1 with system Events.
 * 		Data is a currently-unused attribute earmarked for allowing for more complicated governance schemes.
 *
 */
export interface Policy {
	policy_id: PolicyId;
	role_id: number;
	permission: string;
	data: {
		[k: string]: unknown;
	} | null;
	created: Date;
	updated: Date | null;
}

// generated by src/lib/vocab/policy/policy.schema.ts
