// generated by src/lib/db/create/createTask.schema.ts

export interface DbCreateTaskArgs {
	seed?: boolean;
	/**
	 * opt out of seeding
	 */
	'no-seed'?: boolean;
}

// generated by src/lib/db/create/createTask.schema.ts
