// generated by src/lib/vocab/space/space.schema.ts

import type {Flavored} from '@feltjs/util';
import type {HubId} from '$lib/vocab/hub/hub';
import type {EntityId} from '$lib/vocab/entity/entity';

export type SpaceId = Flavored<number, 'SpaceId'>;

/**
 * Spaces are subdivisions within a Hub that hold a View and reference to an Entity directory.
 * The View is used to interpret, visualize, and manipulate the Entities connected to the directory.
 * Each is a Svelte component that conforms to the View interface.
 */
export interface Space {
	space_id: SpaceId;
	name: string;
	icon: string;
	view: string;
	created: Date;
	updated: Date | null;
	hub_id: HubId;
	directory_id: EntityId;
}

// generated by src/lib/vocab/space/space.schema.ts
