// generated by src/lib/vocab/role/role.schema.ts

import type {Flavored} from '@feltjs/util';
import type {HubId} from '$lib/vocab/hub/hub';

export type RoleId = Flavored<number, 'RoleId'>;

/**
 *
 * 		Roles are user-defined governance objects that exist within the context of a single Hub.
 * 		They have Policies associated with them that allow for actions to be taken within the system.
 * 		When an Actor has a Role via an Assignment, that actor may take any action allowed by the Role's Policies.
 *
 */
export interface Role {
	role_id: RoleId;
	hub_id: HubId;
	name: string;
	created: Date;
	updated: Date | null;
}

// generated by src/lib/vocab/role/role.schema.ts
