// generated by src/lib/vocab/role/role.schema.ts

/**
 *
 * 		Roles are user-defined governance objects that exist within the context of a single Community.
 * 		They have Policies associated with them that allow for actions to be taken within the system.
 * 		When a Persona has a Role via an Assignment, that actor may take any action allowed by the Role's Policies.
 *
 */
export interface Role {
	role_id: number;
	community_id: number;
	name: string;
	created: Date;
	updated: Date | null;
}

// generated by src/lib/vocab/role/role.schema.ts
