// generated by src/lib/server/servicesMeta.gen.ts

// this module is a client-friendly subset of data from '$lib/server/services.ts'

export interface ServiceMeta {
	name: string;
	route: {
		path: string;
		method: string;
	};
}

export const create_persona: ServiceMeta = {
	name: 'create_persona',
	route: {
		path: '/api/v1/personas',
		method: 'POST',
	},
};

export const create_community: ServiceMeta = {
	name: 'create_community',
	route: {
		path: '/api/v1/communities',
		method: 'POST',
	},
};

export const create_membership: ServiceMeta = {
	name: 'create_membership',
	route: {
		path: '/api/v1/memberships',
		method: 'POST',
	},
};

export const create_space: ServiceMeta = {
	name: 'create_space',
	route: {
		path: '/api/v1/communities/:community_id/spaces',
		method: 'POST',
	},
};

export const create_file: ServiceMeta = {
	name: 'create_file',
	route: {
		path: '/api/v1/spaces/:space_id/files',
		method: 'POST',
	},
};

export const read_community: ServiceMeta = {
	name: 'read_community',
	route: {
		path: '/api/v1/communities/:community_id',
		method: 'GET',
	},
};

export const read_communities: ServiceMeta = {
	name: 'read_communities',
	route: {
		path: '/api/v1/communities',
		method: 'GET',
	},
};

export const read_space: ServiceMeta = {
	name: 'read_space',
	route: {
		path: '/api/v1/spaces/:space_id',
		method: 'GET',
	},
};

export const read_spaces: ServiceMeta = {
	name: 'read_spaces',
	route: {
		path: '/api/v1/communities/:community_id/spaces',
		method: 'GET',
	},
};

export const read_files: ServiceMeta = {
	name: 'read_files',
	route: {
		path: '/api/v1/spaces/:space_id/files',
		method: 'GET',
	},
};
