import type {Gen} from '@feltcoop/gro/dist/gen/gen.js';
import {toRootPath} from '@feltcoop/gro/dist/paths.js';

import {services} from '$lib/server/services';

// Outputs a file with services metadata that can be imported from the client.
export const gen: Gen = async ({originId}) => {
	// TODO we're not currently including the schemas since we don't yet use them on the client
	// import type {AnySchema} from 'ajv';
	// paramsSchema: AnySchema;
	// responseSchema: AnySchema;
	// paramsSchema: ${JSON.stringify(service.paramsSchema)},
	// responseSchema: ${JSON.stringify(service.responseSchema)},
	return `
// generated by ${toRootPath(originId)}
  
// this module is a client-friendly subset of data from '$lib/server/services.ts'

export interface ServiceMeta {
  name: string;
  route: {
    path: string;
    method: string;
  };
}

${Array.from(services.values()).reduce(
	(str, service) =>
		str +
		`
export const ${service.name}: ServiceMeta = {
  name: '${service.name}',
  route: {
    path: '${service.route.path}',
    method: '${service.route.method}',
  },
};
`,
	'',
)}

  `.trim();
};
