// generated by src/lib/vocab/membership/membership.schema.ts

export interface Membership {
	persona_id: number;
	community_id: number;
	created: Date;
	updated: Date | null;
}

// generated by src/lib/vocab/membership/membership.schema.ts
