// generated by src/lib/vocab/membership/membership.schema.ts

export interface Membership {
	membership_id: number;
	persona_id: number;
	community_id: number;
	created: Date;
}

// generated by src/lib/vocab/membership/membership.schema.ts
