import type {Gen} from '@feltcoop/gro/dist/gen/gen.js';
import {toRootPath} from '@feltcoop/gro/dist/paths.js';

import {events} from '$lib/ui/eventData.events';

// Outputs a file with services metadata that can be imported from the client.
export const gen: Gen = async ({originId}) => {
	// TODO we're not currently including the schemas since we don't yet use them on the client
	// import type {AnySchema} from 'ajv';
	// paramsSchema: AnySchema;
	// responseSchema: AnySchema;
	// paramsSchema: ${JSON.stringify(service.paramsSchema)},
	// responseSchema: ${JSON.stringify(service.responseSchema)},
	return `
// generated by ${toRootPath(originId)}
  
import type {Readable} from 'svelte/store';
import type {Static} from '@sinclair/typebox';

import type {ClientAccountSession} from '$lib/session/clientSession';
import type {File} from '$lib/vocab/file/file';
import type {ApiResult} from '$lib/server/api';
import type {createCommunityService} from '$lib/vocab/community/communityServices';
import type {createPersonaService} from '$lib/vocab/persona/personaServices';
import type {createMembershipService} from '$lib/vocab/community/communityServices';
import type {createSpaceService} from '$lib/vocab/space/spaceServices';
import type {createFileService, readFilesService} from '$lib/vocab/file/fileServices';
import type {DispatchContext} from '$lib/ui/api';
import type {LoginRequest} from '$lib/session/loginMiddleware.js';
import type {MainNavView} from './ui';

export interface Dispatch {
${events.reduce(
	(str, eventData) =>
		str +
		`
  (
    eventName: '${eventData.name}',
    params: ${eventData.params},
  ): ${eventData.returns};`,
	'',
)}
}

export interface UiHandlers {
  ${events.reduce(
		(str, eventData) =>
			str +
			`
      ${eventData.name}: (
        ctx: DispatchContext<${eventData.params}, ${eventData.result}>,
      ) => ${eventData.returns};`,
		'',
	)}
  };

// generated by ${toRootPath(originId)}
  `.trim();
};
