// generated by src/lib/util/constants.gen.ts

export const DEFAULT_PAGE_SIZE = 20;

// TODO test these values from the database
export const ADMIN_HUB_NAME = 'admin';
export const ADMIN_HUB_ID = 1;
export const ADMIN_ACTOR_ID = 1;
export const GHOST_ACTOR_NAME = 'ghost';
export const GHOST_ACTOR_ID = 2;

export const GUEST_ACTOR_NAME = 'guest';

export const VERSION = '0.12.3';

// generated by src/lib/util/constants.gen.ts
