import type {Gen} from '@feltjs/gro';
import {toRootPath} from '@feltjs/gro/dist/paths.js';

import {actionDatas} from '$lib/vocab/action/actionData';

const toParamsName = (name: string): string => name + 'Params';

// Outputs a file with action types that can be imported from anywhere with no runtime cost.
export const gen: Gen = async ({originId}) => {
	return `
// generated by ${toRootPath(originId)}

import type {RandomVocab, RandomVocabContext} from '$lib/util/randomVocab';
import type {${actionDatas
		.map((e) => toParamsName(e.name))
		.join(',')}} from '$lib/vocab/action/actionTypes';

export interface RandomActionParams {
	${actionDatas.reduce(
		(str, actionData) =>
			str +
			`${
				actionData.name
			}: (random: RandomVocabContext, randomVocab?: RandomVocab) => Promise<${toParamsName(
				actionData.name,
			)}>;`.trim(),
		'',
	)}
}

// generated by ${toRootPath(originId)}
`.trim();
};
