import type {Gen} from '@feltcoop/gro';
import {toRootPath} from '@feltcoop/gro/dist/paths.js';

import {eventInfos} from '$lib/app/events';

const toParamsName = (name: string): string => name + 'Params';

// Outputs a file with event types that can be imported from anywhere with no runtime cost.
export const gen: Gen = async ({originId}) => {
	return `
// generated by ${toRootPath(originId)}

import type {RandomVocab, RandomVocabContext} from '$lib/util/randomVocab';
import type {${eventInfos.map((e) => toParamsName(e.name)).join(',')}} from '$lib/app/eventTypes';

export interface RandomEventParams {
	${eventInfos.reduce(
		(str, eventInfo) =>
			str +
			`${
				eventInfo.name
			}: (random: RandomVocabContext, randomVocab?: RandomVocab) => Promise<${toParamsName(
				eventInfo.name,
			)}>;`.trim(),
		'',
	)}
}

// generated by ${toRootPath(originId)}
`.trim();
};
