// generated by src/lib/vocab/action/actionTypes.gen.ts

import type {
	ClientAccountSession,
	AccountSettings,
	ClientAccount,
	ClientSession,
} from '$lib/vocab/account/account';
import type {ActorId, PublicActor, ClientActor} from '$lib/vocab/actor/actor';
import type {Hub, HubId, HubSettings} from '$lib/vocab/hub/hub';
import type {Role, RoleId} from '$lib/vocab/role/role';
import type {Space, SpaceId} from '$lib/vocab/space/space';
import type {Directory, EntityData} from '$lib/vocab/entity/entityData';
import type {Assignment, AssignmentId} from '$lib/vocab/assignment/assignment';
import type {Policy, PolicyName, PolicyId} from '$lib/vocab/policy/policy';
import type {EntityId, Entity} from '$lib/vocab/entity/entity';
import type {Tie} from '$lib/vocab/tie/tie';
import type {DialogParams} from '@feltjs/felt-ui/dialog.js';
import type {ApiResult} from '$lib/server/api';
import type {
	NonAuthenticatedService,
	NonAuthorizedService,
	AuthorizedService,
} from '$lib/server/service';
import type {MutationContext} from '$lib/ui/mutation';
import type {HubTemplate} from '$lib/ui/templates';

/* eslint-disable @typescript-eslint/array-type */

export type ServiceActionName =
	| 'SignUp'
	| 'SignIn'
	| 'SignOut'
	| 'UpdateAccountSettings'
	| 'UpdateAccountPassword'
	| 'CreateHub'
	| 'ReadHub'
	| 'UpdateHub'
	| 'DeleteHub'
	| 'InviteToHub'
	| 'LeaveHub'
	| 'KickFromHub'
	| 'CreateAccountActor'
	| 'DeleteActor'
	| 'CreateAssignment'
	| 'DeleteAssignment'
	| 'CreateSpace'
	| 'ReadSpaces'
	| 'UpdateSpace'
	| 'DeleteSpace'
	| 'CreateEntity'
	| 'UpdateEntities'
	| 'ReadEntities'
	| 'EraseEntities'
	| 'DeleteEntities'
	| 'ReadEntitiesById'
	| 'CreateRole'
	| 'ReadRoles'
	| 'UpdateRole'
	| 'DeleteRole'
	| 'CreatePolicy'
	| 'ReadPolicies'
	| 'UpdatePolicy'
	| 'DeletePolicy'
	| 'Ping'
	| 'Ephemera';

export type ClientActionName =
	| 'SetSession'
	| 'ToggleMainNav'
	| 'ToggleSecondaryNav'
	| 'SetMobile'
	| 'OpenDialog'
	| 'CloseDialog'
	| 'ViewSpace'
	| 'ClearFreshness';

export interface ActionParamsByName {
	SignUp: SignUpParams;
	SignIn: SignInParams;
	SignOut: SignOutParams;
	UpdateAccountSettings: UpdateAccountSettingsParams;
	UpdateAccountPassword: UpdateAccountPasswordParams;
	CreateHub: CreateHubParams;
	ReadHub: ReadHubParams;
	UpdateHub: UpdateHubParams;
	DeleteHub: DeleteHubParams;
	InviteToHub: InviteToHubParams;
	LeaveHub: LeaveHubParams;
	KickFromHub: KickFromHubParams;
	CreateAccountActor: CreateAccountActorParams;
	DeleteActor: DeleteActorParams;
	CreateAssignment: CreateAssignmentParams;
	DeleteAssignment: DeleteAssignmentParams;
	CreateSpace: CreateSpaceParams;
	ReadSpaces: ReadSpacesParams;
	UpdateSpace: UpdateSpaceParams;
	DeleteSpace: DeleteSpaceParams;
	CreateEntity: CreateEntityParams;
	UpdateEntities: UpdateEntitiesParams;
	ReadEntities: ReadEntitiesParams;
	EraseEntities: EraseEntitiesParams;
	DeleteEntities: DeleteEntitiesParams;
	ReadEntitiesById: ReadEntitiesByIdParams;
	CreateRole: CreateRoleParams;
	ReadRoles: ReadRolesParams;
	UpdateRole: UpdateRoleParams;
	DeleteRole: DeleteRoleParams;
	CreatePolicy: CreatePolicyParams;
	ReadPolicies: ReadPoliciesParams;
	UpdatePolicy: UpdatePolicyParams;
	DeletePolicy: DeletePolicyParams;
	Ping: PingParams;
	Ephemera: EphemeraParams;
	SetSession: SetSessionParams;
	ToggleMainNav: ToggleMainNavParams;
	ToggleSecondaryNav: ToggleSecondaryNavParams;
	SetMobile: SetMobileParams;
	OpenDialog: OpenDialogParams;
	CloseDialog: CloseDialogParams;
	ViewSpace: ViewSpaceParams;
	ClearFreshness: ClearFreshnessParams;
}
export interface ActionResponseByName {
	SignUp: SignUpResponse;
	SignIn: SignInResponse;
	SignOut: SignOutResponse;
	UpdateAccountSettings: UpdateAccountSettingsResponse;
	UpdateAccountPassword: UpdateAccountPasswordResponse;
	CreateHub: CreateHubResponse;
	ReadHub: ReadHubResponse;
	UpdateHub: UpdateHubResponse;
	DeleteHub: DeleteHubResponse;
	InviteToHub: InviteToHubResponse;
	LeaveHub: LeaveHubResponse;
	KickFromHub: KickFromHubResponse;
	CreateAccountActor: CreateAccountActorResponse;
	DeleteActor: DeleteActorResponse;
	CreateAssignment: CreateAssignmentResponse;
	DeleteAssignment: DeleteAssignmentResponse;
	CreateSpace: CreateSpaceResponse;
	ReadSpaces: ReadSpacesResponse;
	UpdateSpace: UpdateSpaceResponse;
	DeleteSpace: DeleteSpaceResponse;
	CreateEntity: CreateEntityResponse;
	UpdateEntities: UpdateEntitiesResponse;
	ReadEntities: ReadEntitiesResponse;
	EraseEntities: EraseEntitiesResponse;
	DeleteEntities: DeleteEntitiesResponse;
	ReadEntitiesById: ReadEntitiesByIdResponse;
	CreateRole: CreateRoleResponse;
	ReadRoles: ReadRolesResponse;
	UpdateRole: UpdateRoleResponse;
	DeleteRole: DeleteRoleResponse;
	CreatePolicy: CreatePolicyResponse;
	ReadPolicies: ReadPoliciesResponse;
	UpdatePolicy: UpdatePolicyResponse;
	DeletePolicy: DeletePolicyResponse;
	Ping: PingResponse;
	Ephemera: EphemeraResponse;
}

export interface ServiceByName {
	Ping: NonAuthorizedService<PingParams, PingResponseResult>;
	Ephemera: AuthorizedService<EphemeraParams, EphemeraResponseResult>;
	SignUp: NonAuthenticatedService<SignUpParams, SignUpResponseResult>;
	SignIn: NonAuthenticatedService<SignInParams, SignInResponseResult>;
	SignOut: NonAuthorizedService<SignOutParams, SignOutResponseResult>;
	UpdateAccountSettings: NonAuthorizedService<
		UpdateAccountSettingsParams,
		UpdateAccountSettingsResponseResult
	>;
	UpdateAccountPassword: NonAuthorizedService<
		UpdateAccountPasswordParams,
		UpdateAccountPasswordResponseResult
	>;
	CreateAccountActor: NonAuthorizedService<
		CreateAccountActorParams,
		CreateAccountActorResponseResult
	>;
	DeleteActor: AuthorizedService<DeleteActorParams, DeleteActorResponseResult>;
	ReadHub: AuthorizedService<ReadHubParams, ReadHubResponseResult>;
	CreateHub: AuthorizedService<CreateHubParams, CreateHubResponseResult>;
	UpdateHub: AuthorizedService<UpdateHubParams, UpdateHubResponseResult>;
	DeleteHub: AuthorizedService<DeleteHubParams, DeleteHubResponseResult>;
	InviteToHub: AuthorizedService<InviteToHubParams, InviteToHubResponseResult>;
	LeaveHub: AuthorizedService<LeaveHubParams, LeaveHubResponseResult>;
	KickFromHub: AuthorizedService<KickFromHubParams, KickFromHubResponseResult>;
	CreateAssignment: AuthorizedService<CreateAssignmentParams, CreateAssignmentResponseResult>;
	DeleteAssignment: AuthorizedService<DeleteAssignmentParams, DeleteAssignmentResponseResult>;
	ReadSpaces: AuthorizedService<ReadSpacesParams, ReadSpacesResponseResult>;
	CreateSpace: AuthorizedService<CreateSpaceParams, CreateSpaceResponseResult>;
	UpdateSpace: AuthorizedService<UpdateSpaceParams, UpdateSpaceResponseResult>;
	DeleteSpace: AuthorizedService<DeleteSpaceParams, DeleteSpaceResponseResult>;
	ReadEntities: AuthorizedService<ReadEntitiesParams, ReadEntitiesResponseResult>;
	CreateEntity: AuthorizedService<CreateEntityParams, CreateEntityResponseResult>;
	UpdateEntities: AuthorizedService<UpdateEntitiesParams, UpdateEntitiesResponseResult>;
	EraseEntities: AuthorizedService<EraseEntitiesParams, EraseEntitiesResponseResult>;
	DeleteEntities: AuthorizedService<DeleteEntitiesParams, DeleteEntitiesResponseResult>;
	ReadEntitiesById: AuthorizedService<ReadEntitiesByIdParams, ReadEntitiesByIdResponseResult>;
	CreateRole: AuthorizedService<CreateRoleParams, CreateRoleResponseResult>;
	ReadRoles: AuthorizedService<ReadRolesParams, ReadRolesResponseResult>;
	UpdateRole: AuthorizedService<UpdateRoleParams, UpdateRoleResponseResult>;
	DeleteRole: AuthorizedService<DeleteRoleParams, DeleteRoleResponseResult>;
	CreatePolicy: AuthorizedService<CreatePolicyParams, CreatePolicyResponseResult>;
	DeletePolicy: AuthorizedService<DeletePolicyParams, DeletePolicyResponseResult>;
	ReadPolicies: AuthorizedService<ReadPoliciesParams, ReadPoliciesResponseResult>;
	UpdatePolicy: AuthorizedService<UpdatePolicyParams, UpdatePolicyResponseResult>;
}

export interface SignUpParams {
	username: string;
	password: string;
}
export interface SignUpResponse {
	/**
	 * The session data loaded on each page for authenticated users.
	 */
	session: ClientAccountSession;
}
export type SignUpResponseResult = ApiResult<SignUpResponse>;

export interface SignInParams {
	username: string;
	password: string;
}
export interface SignInResponse {
	/**
	 * The session data loaded on each page for authenticated users.
	 */
	session: ClientAccountSession;
}
export type SignInResponseResult = ApiResult<SignInResponse>;

export type SignOutParams = null;
export type SignOutResponse = null;
export type SignOutResponseResult = ApiResult<SignOutResponse>;

export interface UpdateAccountSettingsParams {
	/**
	 * A nested set of attributes on <Vocab name="Account" /> and <Vocab name="ClientAccount" />. Holds all account level settings.
	 */
	settings: AccountSettings;
}
/**
 * A client-facing subset of an <Vocab name="Account" />. Excludes <code>password</code> for security.
 */
export type UpdateAccountSettingsResponse = ClientAccount;
export type UpdateAccountSettingsResponseResult = ApiResult<UpdateAccountSettingsResponse>;

export interface UpdateAccountPasswordParams {
	oldPassword: string;
	newPassword: string;
}
/**
 * A client-facing subset of an <Vocab name="Account" />. Excludes <code>password</code> for security.
 */
export type UpdateAccountPasswordResponse = ClientAccount;
export type UpdateAccountPasswordResponseResult = ApiResult<UpdateAccountPasswordResponse>;

export interface CreateHubParams {
	actor: ActorId;
	template: HubTemplate;
}
export interface CreateHubResponse {
	/**
	 * <Vocab name="Hub" />s represent the membrane around the places <Vocab name="Actor" />s can interact with each other or with system level data.
	 * They have self contained governance and ownership of <Vocab name="Space" />s within them.
	 * By default they are hidden and undiscoverable and are only visible to a user once an <Vocab name="Actor" /> has been invited in.
	 */
	hub: Hub;
	roles: Role[];
	spaces: Space[];
	directories: Directory[];
	assignments: Assignment[];
	policies: Policy[];
	actors: PublicActor[];
}
export type CreateHubResponseResult = ApiResult<CreateHubResponse>;

export interface ReadHubParams {
	actor: ActorId;
	hub_id: HubId;
}
export interface ReadHubResponse {
	/**
	 * <Vocab name="Hub" />s represent the membrane around the places <Vocab name="Actor" />s can interact with each other or with system level data.
	 * They have self contained governance and ownership of <Vocab name="Space" />s within them.
	 * By default they are hidden and undiscoverable and are only visible to a user once an <Vocab name="Actor" /> has been invited in.
	 */
	hub: Hub;
	spaces: Space[];
	directories: Directory[];
	roles: Role[];
	assignments: Assignment[];
	actors: PublicActor[];
}
export type ReadHubResponseResult = ApiResult<ReadHubResponse>;

export interface UpdateHubParams {
	actor: ActorId;
	hub_id: HubId;
	/**
	 * A nested set of attributes on <Vocab name="Hub" />. Holds all hub level settings.
	 */
	settings?: HubSettings;
}
export interface UpdateHubResponse {
	/**
	 * <Vocab name="Hub" />s represent the membrane around the places <Vocab name="Actor" />s can interact with each other or with system level data.
	 * They have self contained governance and ownership of <Vocab name="Space" />s within them.
	 * By default they are hidden and undiscoverable and are only visible to a user once an <Vocab name="Actor" /> has been invited in.
	 */
	hub: Hub;
}
export type UpdateHubResponseResult = ApiResult<UpdateHubResponse>;

export interface DeleteHubParams {
	actor: ActorId;
	hub_id: HubId;
}
export type DeleteHubResponse = null;
export type DeleteHubResponseResult = ApiResult<DeleteHubResponse>;

export interface InviteToHubParams {
	actor: ActorId;
	hub_id: HubId;
	name: string;
}
export interface InviteToHubResponse {
	/**
	 * A subset of an <Vocab name="Actor" /> available to all clients in a <Vocab name="Hub" />.
	 */
	actor: PublicActor;
	/**
	 * Describes the relationship between an <Vocab name="Actor" /> and <Vocab name="Role" /> within a given <Vocab name="Hub" />.
	 * An <Vocab name="Actor" /> must have at least 1 <Vocab name="Assignment" /> to be in a <Vocab name="Hub" /> and see it in the nav.
	 * When initially joining a <Vocab name="Hub" />, <Vocab name="Actor" />s are given an <Vocab name="Assignment" /> to the default <Vocab name="Role" />.
	 */
	assignment: Assignment;
}
export type InviteToHubResponseResult = ApiResult<InviteToHubResponse>;

export interface LeaveHubParams {
	actor: ActorId;
	actor_id: ActorId;
	hub_id: HubId;
}
export type LeaveHubResponse = null;
export type LeaveHubResponseResult = ApiResult<LeaveHubResponse>;

export interface KickFromHubParams {
	actor: ActorId;
	actor_id: ActorId;
	hub_id: HubId;
}
export type KickFromHubResponse = null;
export type KickFromHubResponseResult = ApiResult<KickFromHubResponse>;

export interface CreateAccountActorParams {
	name: string;
}
export interface CreateAccountActorResponse {
	actors: ClientActor[];
	hubs: Hub[];
	roles: Role[];
	policies: Policy[];
	spaces: Space[];
	directories: Directory[];
	assignments: Assignment[];
}
export type CreateAccountActorResponseResult = ApiResult<CreateAccountActorResponse>;

export interface DeleteActorParams {
	actor: ActorId;
	actor_id: ActorId;
}
export type DeleteActorResponse = null;
export type DeleteActorResponseResult = ApiResult<DeleteActorResponse>;

export interface CreateAssignmentParams {
	actor: ActorId;
	actor_id: ActorId;
	hub_id: HubId;
	role_id: RoleId;
}
export interface CreateAssignmentResponse {
	/**
	 * Describes the relationship between an <Vocab name="Actor" /> and <Vocab name="Role" /> within a given <Vocab name="Hub" />.
	 * An <Vocab name="Actor" /> must have at least 1 <Vocab name="Assignment" /> to be in a <Vocab name="Hub" /> and see it in the nav.
	 * When initially joining a <Vocab name="Hub" />, <Vocab name="Actor" />s are given an <Vocab name="Assignment" /> to the default <Vocab name="Role" />.
	 */
	assignment: Assignment;
}
export type CreateAssignmentResponseResult = ApiResult<CreateAssignmentResponse>;

export interface DeleteAssignmentParams {
	actor: ActorId;
	assignment_id: AssignmentId;
}
export type DeleteAssignmentResponse = null;
export type DeleteAssignmentResponseResult = ApiResult<DeleteAssignmentResponse>;

export interface CreateSpaceParams {
	actor: ActorId;
	hub_id: HubId;
	name: string;
	path: string;
	icon: string;
	view: string;
}
export interface CreateSpaceResponse {
	/**
	 * <Vocab name="Space" />s are subdivisions within a <Vocab name="Hub" /> that hold a View and reference to an <Vocab name="Entity" /> directory.
	 * The View is used to interpret, visualize, and manipulate the <Vocab name="Entity" />s connected to the directory.
	 * Each is a Svelte component that conforms to the View interface.
	 */
	space: Space;
	/**
	 * An <Vocab name="Entity" /> is the core data type that represents an ActivityStreams object in the system.
	 * Each has an "owning" space and actor that controls its governance.
	 * <Vocab name="Entity" /> objects exist within a graph architecture, with <Vocab name="Tie" /> objects serving as the edges between nodes.
	 * Conventionally, all entities within a given <Vocab name="Space" /> can be found by traversing
	 * the graph starting at the directory <Vocab name="Entity" /> associated with the owning <Vocab name="Space" />.
	 * A directory is an ActivityStreams Collection referenced by each <Vocab name="Space" />.
	 */
	directory: Directory;
}
export type CreateSpaceResponseResult = ApiResult<CreateSpaceResponse>;

export interface ReadSpacesParams {
	actor: ActorId;
	hub_id: HubId;
}
export interface ReadSpacesResponse {
	spaces: Space[];
	directories: Directory[];
}
export type ReadSpacesResponseResult = ApiResult<ReadSpacesResponse>;

export interface UpdateSpaceParams {
	actor: ActorId;
	space_id: SpaceId;
	name?: string;
	path?: string;
	icon?: string;
	view?: string;
}
export interface UpdateSpaceResponse {
	/**
	 * <Vocab name="Space" />s are subdivisions within a <Vocab name="Hub" /> that hold a View and reference to an <Vocab name="Entity" /> directory.
	 * The View is used to interpret, visualize, and manipulate the <Vocab name="Entity" />s connected to the directory.
	 * Each is a Svelte component that conforms to the View interface.
	 */
	space: Space;
}
export type UpdateSpaceResponseResult = ApiResult<UpdateSpaceResponse>;

export interface DeleteSpaceParams {
	actor: ActorId;
	space_id: SpaceId;
}
export type DeleteSpaceResponse = null;
export type DeleteSpaceResponseResult = ApiResult<DeleteSpaceResponse>;

export interface CreateEntityParams {
	actor: ActorId;
	space_id: SpaceId;
	path?: string | null;
	data: EntityData;
	ties?: (
		| {
				source_id: EntityId;
				type?: string;
		  }
		| {
				dest_id: EntityId;
				type?: string;
		  }
	)[];
}
export interface CreateEntityResponse {
	entities: Entity[];
	ties: Tie[];
}
export type CreateEntityResponseResult = ApiResult<CreateEntityResponse>;

export interface UpdateEntitiesParams {
	actor: ActorId;
	entities: {
		entity_id: EntityId;
		data?: EntityData;
		path?: string | null;
	}[];
}
export interface UpdateEntitiesResponse {
	entities: Entity[];
}
export type UpdateEntitiesResponseResult = ApiResult<UpdateEntitiesResponse>;

export interface ReadEntitiesParams {
	actor: ActorId;
	source_id: EntityId;
	pageSize?: number;
	pageKey?: number;
	related?: 'source' | 'dest' | 'both';
	orderBy?: 'newest' | 'oldest';
}
export interface ReadEntitiesResponse {
	entities: Entity[];
	ties: Tie[];
	more: boolean;
}
export type ReadEntitiesResponseResult = ApiResult<ReadEntitiesResponse>;

export interface EraseEntitiesParams {
	actor: ActorId;
	entityIds: EntityId[];
}
export interface EraseEntitiesResponse {
	entities: Entity[];
}
export type EraseEntitiesResponseResult = ApiResult<EraseEntitiesResponse>;

export interface DeleteEntitiesParams {
	actor: ActorId;
	entityIds: EntityId[];
}
export interface DeleteEntitiesResponse {
	entities: Entity[];
	deleted: EntityId[];
}
export type DeleteEntitiesResponseResult = ApiResult<DeleteEntitiesResponse>;

export interface ReadEntitiesByIdParams {
	actor: ActorId;
	entityIds: EntityId[];
}
export interface ReadEntitiesByIdResponse {
	entities: Entity[];
}
export type ReadEntitiesByIdResponseResult = ApiResult<ReadEntitiesByIdResponse>;

export interface CreateRoleParams {
	actor: ActorId;
	hub_id: HubId;
	name: string;
}
export interface CreateRoleResponse {
	/**
	 * <Vocab name="Role" />s are user-defined governance objects that exist within the context of a single <Vocab name="Hub" />.
	 * They have <Vocab name="Policy" />s associated with them that allow for actions to be taken within the system.
	 * When an <Vocab name="Actor" /> has a <Vocab name="Role" /> via an <Vocab name="Assignment" />,
	 * that actor may take any action allowed by the role's <Vocab name="Policy" />s.
	 */
	role: Role;
}
export type CreateRoleResponseResult = ApiResult<CreateRoleResponse>;

export interface ReadRolesParams {
	actor: ActorId;
	hub_id: HubId;
}
export interface ReadRolesResponse {
	roles: Role[];
}
export type ReadRolesResponseResult = ApiResult<ReadRolesResponse>;

export interface UpdateRoleParams {
	actor: ActorId;
	role_id: RoleId;
	name: string;
}
export interface UpdateRoleResponse {
	/**
	 * <Vocab name="Role" />s are user-defined governance objects that exist within the context of a single <Vocab name="Hub" />.
	 * They have <Vocab name="Policy" />s associated with them that allow for actions to be taken within the system.
	 * When an <Vocab name="Actor" /> has a <Vocab name="Role" /> via an <Vocab name="Assignment" />,
	 * that actor may take any action allowed by the role's <Vocab name="Policy" />s.
	 */
	role: Role;
}
export type UpdateRoleResponseResult = ApiResult<UpdateRoleResponse>;

export interface DeleteRoleParams {
	actor: ActorId;
	role_id: RoleId;
}
export type DeleteRoleResponse = null;
export type DeleteRoleResponseResult = ApiResult<DeleteRoleResponse>;

export interface CreatePolicyParams {
	actor: ActorId;
	role_id: RoleId;
	name: PolicyName;
}
export interface CreatePolicyResponse {
	/**
	 * Each <Vocab name="Policy" /> associates a <Vocab name="Role" /> with a name
	 * to describe the Actions that <Vocab name="Actor" />s with the <Vocab name="Role" /> are able to perform.
	 * Policies are often 1:1 with Actions, but they don't have to be.
	 * `data` is a stub to support more complex governance schemes in the future.
	 */
	policy: Policy;
}
export type CreatePolicyResponseResult = ApiResult<CreatePolicyResponse>;

export interface ReadPoliciesParams {
	actor: ActorId;
	role_id: RoleId;
}
export interface ReadPoliciesResponse {
	policies: Policy[];
}
export type ReadPoliciesResponseResult = ApiResult<ReadPoliciesResponse>;

export interface UpdatePolicyParams {
	actor: ActorId;
	policy_id: PolicyId;
	data: {
		[k: string]: unknown;
	} | null;
}
export interface UpdatePolicyResponse {
	/**
	 * Each <Vocab name="Policy" /> associates a <Vocab name="Role" /> with a name
	 * to describe the Actions that <Vocab name="Actor" />s with the <Vocab name="Role" /> are able to perform.
	 * Policies are often 1:1 with Actions, but they don't have to be.
	 * `data` is a stub to support more complex governance schemes in the future.
	 */
	policy: Policy;
}
export type UpdatePolicyResponseResult = ApiResult<UpdatePolicyResponse>;

export interface DeletePolicyParams {
	actor: ActorId;
	policy_id: PolicyId;
}
export type DeletePolicyResponse = null;
export type DeletePolicyResponseResult = ApiResult<DeletePolicyResponse>;

export type PingParams = null;
export type PingResponse = null;
export type PingResponseResult = ApiResult<PingResponse>;

export interface EphemeraParams {
	actor: ActorId;
	space_id: SpaceId;
	data: {
		type: string;
		[k: string]: unknown;
	};
}
export interface EphemeraResponse {
	actor: ActorId;
	space_id: SpaceId;
	data: {
		type: string;
		[k: string]: unknown;
	};
}
export type EphemeraResponseResult = ApiResult<EphemeraResponse>;

export interface SetSessionParams {
	/**
	 * The session data loaded on each page for authenticated and unauthenticated users.
	 */
	session: ClientSession;
}

export type ToggleMainNavParams = void;

export type ToggleSecondaryNavParams = void;

export type SetMobileParams = boolean;

export type OpenDialogParams = DialogParams;

export type CloseDialogParams = void;

export interface ViewSpaceParams {
	space_id: SpaceId;
	view: string | null;
}

export interface ClearFreshnessParams {
	directory_id: EntityId;
}

export interface Actions {
	SignUp: (params: SignUpParams) => Promise<SignUpResponseResult>;
	SignIn: (params: SignInParams) => Promise<SignInResponseResult>;
	SignOut: () => Promise<SignOutResponseResult>;
	UpdateAccountSettings: (
		params: UpdateAccountSettingsParams,
	) => Promise<UpdateAccountSettingsResponseResult>;
	UpdateAccountPassword: (
		params: UpdateAccountPasswordParams,
	) => Promise<UpdateAccountPasswordResponseResult>;
	CreateHub: (params: CreateHubParams) => Promise<CreateHubResponseResult>;
	ReadHub: (params: ReadHubParams) => Promise<ReadHubResponseResult>;
	UpdateHub: (params: UpdateHubParams) => Promise<UpdateHubResponseResult>;
	DeleteHub: (params: DeleteHubParams) => Promise<DeleteHubResponseResult>;
	InviteToHub: (params: InviteToHubParams) => Promise<InviteToHubResponseResult>;
	LeaveHub: (params: LeaveHubParams) => Promise<LeaveHubResponseResult>;
	KickFromHub: (params: KickFromHubParams) => Promise<KickFromHubResponseResult>;
	CreateAccountActor: (
		params: CreateAccountActorParams,
	) => Promise<CreateAccountActorResponseResult>;
	DeleteActor: (params: DeleteActorParams) => Promise<DeleteActorResponseResult>;
	CreateAssignment: (params: CreateAssignmentParams) => Promise<CreateAssignmentResponseResult>;
	DeleteAssignment: (params: DeleteAssignmentParams) => Promise<DeleteAssignmentResponseResult>;
	CreateSpace: (params: CreateSpaceParams) => Promise<CreateSpaceResponseResult>;
	ReadSpaces: (params: ReadSpacesParams) => Promise<ReadSpacesResponseResult>;
	UpdateSpace: (params: UpdateSpaceParams) => Promise<UpdateSpaceResponseResult>;
	DeleteSpace: (params: DeleteSpaceParams) => Promise<DeleteSpaceResponseResult>;
	CreateEntity: (params: CreateEntityParams) => Promise<CreateEntityResponseResult>;
	UpdateEntities: (params: UpdateEntitiesParams) => Promise<UpdateEntitiesResponseResult>;
	ReadEntities: (params: ReadEntitiesParams) => Promise<ReadEntitiesResponseResult>;
	EraseEntities: (params: EraseEntitiesParams) => Promise<EraseEntitiesResponseResult>;
	DeleteEntities: (params: DeleteEntitiesParams) => Promise<DeleteEntitiesResponseResult>;
	ReadEntitiesById: (params: ReadEntitiesByIdParams) => Promise<ReadEntitiesByIdResponseResult>;
	CreateRole: (params: CreateRoleParams) => Promise<CreateRoleResponseResult>;
	ReadRoles: (params: ReadRolesParams) => Promise<ReadRolesResponseResult>;
	UpdateRole: (params: UpdateRoleParams) => Promise<UpdateRoleResponseResult>;
	DeleteRole: (params: DeleteRoleParams) => Promise<DeleteRoleResponseResult>;
	CreatePolicy: (params: CreatePolicyParams) => Promise<CreatePolicyResponseResult>;
	ReadPolicies: (params: ReadPoliciesParams) => Promise<ReadPoliciesResponseResult>;
	UpdatePolicy: (params: UpdatePolicyParams) => Promise<UpdatePolicyResponseResult>;
	DeletePolicy: (params: DeletePolicyParams) => Promise<DeletePolicyResponseResult>;
	Ping: () => Promise<ApiResult<null>>;
	Ephemera: (params: EphemeraParams) => Promise<EphemeraResponseResult>;
	SetSession: (params: SetSessionParams) => void;
	ToggleMainNav: (params: ToggleMainNavParams) => void;
	ToggleSecondaryNav: (params: ToggleSecondaryNavParams) => void;
	SetMobile: (params: SetMobileParams) => void;
	OpenDialog: (params: OpenDialogParams) => void;
	CloseDialog: (params: CloseDialogParams) => void;
	ViewSpace: (params: ViewSpaceParams) => void;
	ClearFreshness: (params: ClearFreshnessParams) => void;
}

export interface Mutations {
	SignUp: (
		ctx: MutationContext<SignUpParams, SignUpResponseResult>,
	) => Promise<SignUpResponseResult>;
	SignIn: (
		ctx: MutationContext<SignInParams, SignInResponseResult>,
	) => Promise<SignInResponseResult>;
	SignOut: (
		ctx: MutationContext<SignOutParams, SignOutResponseResult>,
	) => Promise<SignOutResponseResult>;
	UpdateAccountSettings: (
		ctx: MutationContext<UpdateAccountSettingsParams, UpdateAccountSettingsResponseResult>,
	) => Promise<UpdateAccountSettingsResponseResult>;
	UpdateAccountPassword: (
		ctx: MutationContext<UpdateAccountPasswordParams, UpdateAccountPasswordResponseResult>,
	) => Promise<UpdateAccountPasswordResponseResult>;
	CreateHub: (
		ctx: MutationContext<CreateHubParams, CreateHubResponseResult>,
	) => Promise<CreateHubResponseResult>;
	ReadHub: (
		ctx: MutationContext<ReadHubParams, ReadHubResponseResult>,
	) => Promise<ReadHubResponseResult>;
	UpdateHub: (
		ctx: MutationContext<UpdateHubParams, UpdateHubResponseResult>,
	) => Promise<UpdateHubResponseResult>;
	DeleteHub: (
		ctx: MutationContext<DeleteHubParams, DeleteHubResponseResult>,
	) => Promise<DeleteHubResponseResult>;
	InviteToHub: (
		ctx: MutationContext<InviteToHubParams, InviteToHubResponseResult>,
	) => Promise<InviteToHubResponseResult>;
	LeaveHub: (
		ctx: MutationContext<LeaveHubParams, LeaveHubResponseResult>,
	) => Promise<LeaveHubResponseResult>;
	KickFromHub: (
		ctx: MutationContext<KickFromHubParams, KickFromHubResponseResult>,
	) => Promise<KickFromHubResponseResult>;
	CreateAccountActor: (
		ctx: MutationContext<CreateAccountActorParams, CreateAccountActorResponseResult>,
	) => Promise<CreateAccountActorResponseResult>;
	DeleteActor: (
		ctx: MutationContext<DeleteActorParams, DeleteActorResponseResult>,
	) => Promise<DeleteActorResponseResult>;
	CreateAssignment: (
		ctx: MutationContext<CreateAssignmentParams, CreateAssignmentResponseResult>,
	) => Promise<CreateAssignmentResponseResult>;
	DeleteAssignment: (
		ctx: MutationContext<DeleteAssignmentParams, DeleteAssignmentResponseResult>,
	) => Promise<DeleteAssignmentResponseResult>;
	CreateSpace: (
		ctx: MutationContext<CreateSpaceParams, CreateSpaceResponseResult>,
	) => Promise<CreateSpaceResponseResult>;
	ReadSpaces: (
		ctx: MutationContext<ReadSpacesParams, ReadSpacesResponseResult>,
	) => Promise<ReadSpacesResponseResult>;
	UpdateSpace: (
		ctx: MutationContext<UpdateSpaceParams, UpdateSpaceResponseResult>,
	) => Promise<UpdateSpaceResponseResult>;
	DeleteSpace: (
		ctx: MutationContext<DeleteSpaceParams, DeleteSpaceResponseResult>,
	) => Promise<DeleteSpaceResponseResult>;
	CreateEntity: (
		ctx: MutationContext<CreateEntityParams, CreateEntityResponseResult>,
	) => Promise<CreateEntityResponseResult>;
	UpdateEntities: (
		ctx: MutationContext<UpdateEntitiesParams, UpdateEntitiesResponseResult>,
	) => Promise<UpdateEntitiesResponseResult>;
	ReadEntities: (
		ctx: MutationContext<ReadEntitiesParams, ReadEntitiesResponseResult>,
	) => Promise<ReadEntitiesResponseResult>;
	EraseEntities: (
		ctx: MutationContext<EraseEntitiesParams, EraseEntitiesResponseResult>,
	) => Promise<EraseEntitiesResponseResult>;
	DeleteEntities: (
		ctx: MutationContext<DeleteEntitiesParams, DeleteEntitiesResponseResult>,
	) => Promise<DeleteEntitiesResponseResult>;
	ReadEntitiesById: (
		ctx: MutationContext<ReadEntitiesByIdParams, ReadEntitiesByIdResponseResult>,
	) => Promise<ReadEntitiesByIdResponseResult>;
	CreateRole: (
		ctx: MutationContext<CreateRoleParams, CreateRoleResponseResult>,
	) => Promise<CreateRoleResponseResult>;
	ReadRoles: (
		ctx: MutationContext<ReadRolesParams, ReadRolesResponseResult>,
	) => Promise<ReadRolesResponseResult>;
	UpdateRole: (
		ctx: MutationContext<UpdateRoleParams, UpdateRoleResponseResult>,
	) => Promise<UpdateRoleResponseResult>;
	DeleteRole: (
		ctx: MutationContext<DeleteRoleParams, DeleteRoleResponseResult>,
	) => Promise<DeleteRoleResponseResult>;
	CreatePolicy: (
		ctx: MutationContext<CreatePolicyParams, CreatePolicyResponseResult>,
	) => Promise<CreatePolicyResponseResult>;
	ReadPolicies: (
		ctx: MutationContext<ReadPoliciesParams, ReadPoliciesResponseResult>,
	) => Promise<ReadPoliciesResponseResult>;
	UpdatePolicy: (
		ctx: MutationContext<UpdatePolicyParams, UpdatePolicyResponseResult>,
	) => Promise<UpdatePolicyResponseResult>;
	DeletePolicy: (
		ctx: MutationContext<DeletePolicyParams, DeletePolicyResponseResult>,
	) => Promise<DeletePolicyResponseResult>;
	Ping: (ctx: MutationContext<PingParams, PingResponseResult>) => Promise<ApiResult<null>>;
	Ephemera: (
		ctx: MutationContext<EphemeraParams, EphemeraResponseResult>,
	) => Promise<EphemeraResponseResult>;
	SetSession: (ctx: MutationContext<SetSessionParams, void>) => void;
	ToggleMainNav: (ctx: MutationContext<ToggleMainNavParams, void>) => void;
	ToggleSecondaryNav: (ctx: MutationContext<ToggleSecondaryNavParams, void>) => void;
	SetMobile: (ctx: MutationContext<SetMobileParams, void>) => void;
	OpenDialog: (ctx: MutationContext<OpenDialogParams, void>) => void;
	CloseDialog: (ctx: MutationContext<CloseDialogParams, void>) => void;
	ViewSpace: (ctx: MutationContext<ViewSpaceParams, void>) => void;
	ClearFreshness: (ctx: MutationContext<ClearFreshnessParams, void>) => void;
}

// generated by src/lib/vocab/action/actionTypes.gen.ts
